// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Breadcrumbs } from '@tale-ui/react-native/breadcrumbs';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { BreadcrumbsAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.breadcrumbs;
const meta = {
  title: 'Components/Navigation/Breadcrumbs',
  component: Breadcrumbs,
  args: controls.args as Partial<React.ComponentProps<typeof Breadcrumbs>>,
  argTypes: controls.argTypes as Meta<typeof Breadcrumbs>['argTypes'],
  parameters: {
    nativeComponent: 'breadcrumbs',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Breadcrumbs>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="breadcrumbs" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
