// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Pagination } from '@tale-ui/react-native/pagination';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { PaginationAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.pagination;
const meta = {
  title: 'Components/Navigation/Pagination',
  component: Pagination,
  args: controls.args as Partial<React.ComponentProps<typeof Pagination>>,
  argTypes: controls.argTypes as Meta<typeof Pagination>['argTypes'],
  parameters: {
    nativeComponent: 'pagination',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Pagination>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="pagination" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
