// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Button } from '@tale-ui/react-native/button';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ButtonAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.button;
const meta = {
  title: 'Components/Form Controls/Button',
  component: Button,
  args: controls.args as Partial<React.ComponentProps<typeof Button>>,
  argTypes: controls.argTypes as Meta<typeof Button>['argTypes'],
  parameters: {
    nativeComponent: 'button',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="button" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
