// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { CheckboxField } from '@tale-ui/react-native/checkbox-field';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { CheckboxFieldAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['checkbox-field'];
const meta = {
  title: 'Components/Form Controls/CheckboxField',
  component: CheckboxField,
  args: controls.args as Partial<React.ComponentProps<typeof CheckboxField>>,
  argTypes: controls.argTypes as Meta<typeof CheckboxField>['argTypes'],
  parameters: {
    nativeComponent: 'checkbox-field',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof CheckboxField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="checkbox-field" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
