// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { CheckboxGroup } from '@tale-ui/react-native/checkbox-group';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { CheckboxGroupAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['checkbox-group'];
const meta = {
  title: 'Components/Form Controls/CheckboxGroup',
  component: CheckboxGroup,
  args: controls.args as Partial<React.ComponentProps<typeof CheckboxGroup>>,
  argTypes: controls.argTypes as Meta<typeof CheckboxGroup>['argTypes'],
  parameters: {
    nativeComponent: 'checkbox-group',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof CheckboxGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="checkbox-group" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
