// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Input } from '@tale-ui/react-native/input';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { InputAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.input;
const meta = {
  title: 'Components/Form Controls/Input',
  component: Input,
  args: controls.args as Partial<React.ComponentProps<typeof Input>>,
  argTypes: controls.argTypes as Meta<typeof Input>['argTypes'],
  parameters: {
    nativeComponent: 'input',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Input>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="input" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
