// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { RadioGroup } from '@tale-ui/react-native/radio-group';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { RadioGroupAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['radio-group'];
const meta = {
  title: 'Components/Form Controls/RadioGroup',
  component: RadioGroup,
  args: controls.args as Partial<React.ComponentProps<typeof RadioGroup>>,
  argTypes: controls.argTypes as Meta<typeof RadioGroup>['argTypes'],
  parameters: {
    nativeComponent: 'radio-group',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof RadioGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="radio-group" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
