// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { RadioGroup as RadioField } from '@tale-ui/react-native/radio-field';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { RadioFieldAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['radio-field'];
const meta = {
  title: 'Components/Form Controls/RadioField',
  component: RadioField,
  args: controls.args as Partial<React.ComponentProps<typeof RadioField>>,
  argTypes: controls.argTypes as Meta<typeof RadioField>['argTypes'],
  parameters: {
    nativeComponent: 'radio-field',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof RadioField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="radio-field" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
