// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { SearchField } from '@tale-ui/react-native/search-field';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SearchFieldAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['search-field'];
const meta = {
  title: 'Components/Form Controls/SearchField',
  component: SearchField,
  args: controls.args as Partial<React.ComponentProps<typeof SearchField>>,
  argTypes: controls.argTypes as Meta<typeof SearchField>['argTypes'],
  parameters: {
    nativeComponent: 'search-field',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof SearchField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="search-field" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
