// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Slider } from '@tale-ui/react-native/slider';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SliderAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.slider;
const meta = {
  title: 'Components/Form Controls/Slider',
  component: Slider,
  args: controls.args as Partial<React.ComponentProps<typeof Slider>>,
  argTypes: controls.argTypes as Meta<typeof Slider>['argTypes'],
  parameters: {
    nativeComponent: 'slider',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Slider>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="slider" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
