// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { SwitchField } from '@tale-ui/react-native/switch-field';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SwitchFieldAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['switch-field'];
const meta = {
  title: 'Components/Form Controls/SwitchField',
  component: SwitchField,
  args: controls.args as Partial<React.ComponentProps<typeof SwitchField>>,
  argTypes: controls.argTypes as Meta<typeof SwitchField>['argTypes'],
  parameters: {
    nativeComponent: 'switch-field',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof SwitchField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="switch-field" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
