// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { TextArea } from '@tale-ui/react-native/text-area';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { TextAreaAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['text-area'];
const meta = {
  title: 'Components/Form Controls/TextArea',
  component: TextArea,
  args: controls.args as Partial<React.ComponentProps<typeof TextArea>>,
  argTypes: controls.argTypes as Meta<typeof TextArea>['argTypes'],
  parameters: {
    nativeComponent: 'text-area',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof TextArea>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="text-area" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
