// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { ToggleButton } from '@tale-ui/react-native/toggle-button';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ToggleButtonAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['toggle-button'];
const meta = {
  title: 'Components/Form Controls/ToggleButton',
  component: ToggleButton,
  args: controls.args as Partial<React.ComponentProps<typeof ToggleButton>>,
  argTypes: controls.argTypes as Meta<typeof ToggleButton>['argTypes'],
  parameters: {
    nativeComponent: 'toggle-button',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof ToggleButton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="toggle-button" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
