// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { ToggleButtonGroup } from '@tale-ui/react-native/toggle-group';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ToggleButtonGroupAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['toggle-group'];
const meta = {
  title: 'Components/Form Controls/ToggleButtonGroup',
  component: ToggleButtonGroup,
  args: controls.args as Partial<React.ComponentProps<typeof ToggleButtonGroup>>,
  argTypes: controls.argTypes as Meta<typeof ToggleButtonGroup>['argTypes'],
  parameters: {
    nativeComponent: 'toggle-group',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof ToggleButtonGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="toggle-group" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
