// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Text } from '@tale-ui/react-native/text';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { TextAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.text;
const meta = {
  title: 'Components/Typography/Text',
  component: Text,
  args: controls.args as Partial<React.ComponentProps<typeof Text>>,
  argTypes: controls.argTypes as Meta<typeof Text>['argTypes'],
  parameters: {
    nativeComponent: 'text',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Text>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="text" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
