// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Accordion } from '@tale-ui/react-native/accordion';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { AccordionAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.accordion;
const meta = {
  title: 'Components/Layout/Accordion',
  component: Accordion,
  args: controls.args as Partial<React.ComponentProps<typeof Accordion>>,
  argTypes: controls.argTypes as Meta<typeof Accordion>['argTypes'],
  parameters: {
    nativeComponent: 'accordion',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Accordion>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="accordion" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
