// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Card } from '@tale-ui/react-native/card';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { CardAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.card;
const meta = {
  title: 'Components/Layout/Card',
  component: Card,
  args: controls.args as Partial<React.ComponentProps<typeof Card>>,
  argTypes: controls.argTypes as Meta<typeof Card>['argTypes'],
  parameters: {
    nativeComponent: 'card',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Card>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="card" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
