// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Column } from '@tale-ui/react-native/column';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ColumnAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.column;
const meta = {
  title: 'Components/Layout/Column',
  component: Column,
  args: controls.args as Partial<React.ComponentProps<typeof Column>>,
  argTypes: controls.argTypes as Meta<typeof Column>['argTypes'],
  parameters: {
    nativeComponent: 'column',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Column>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="column" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
