// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Disclosure } from '@tale-ui/react-native/disclosure';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { DisclosureAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.disclosure;
const meta = {
  title: 'Components/Layout/Disclosure',
  component: Disclosure,
  args: controls.args as Partial<React.ComponentProps<typeof Disclosure>>,
  argTypes: controls.argTypes as Meta<typeof Disclosure>['argTypes'],
  parameters: {
    nativeComponent: 'disclosure',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Disclosure>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="disclosure" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
