// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Separator } from '@tale-ui/react-native/separator';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SeparatorAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.separator;
const meta = {
  title: 'Components/Layout/Separator',
  component: Separator,
  args: controls.args as Partial<React.ComponentProps<typeof Separator>>,
  argTypes: controls.argTypes as Meta<typeof Separator>['argTypes'],
  parameters: {
    nativeComponent: 'separator',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Separator>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="separator" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
