// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Tabs } from '@tale-ui/react-native/tabs';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { TabsAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.tabs;
const meta = {
  title: 'Components/Layout/Tabs',
  component: Tabs,
  args: controls.args as Partial<React.ComponentProps<typeof Tabs>>,
  argTypes: controls.argTypes as Meta<typeof Tabs>['argTypes'],
  parameters: {
    nativeComponent: 'tabs',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Tabs>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="tabs" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
