// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Toolbar } from '@tale-ui/react-native/toolbar';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ToolbarAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.toolbar;
const meta = {
  title: 'Components/Layout/Toolbar',
  component: Toolbar,
  args: controls.args as Partial<React.ComponentProps<typeof Toolbar>>,
  argTypes: controls.argTypes as Meta<typeof Toolbar>['argTypes'],
  parameters: {
    nativeComponent: 'toolbar',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Toolbar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="toolbar" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
