// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Badge } from '@tale-ui/react-native/badge';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { BadgeAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.badge;
const meta = {
  title: 'Components/Display/Badge',
  component: Badge,
  args: controls.args as Partial<React.ComponentProps<typeof Badge>>,
  argTypes: controls.argTypes as Meta<typeof Badge>['argTypes'],
  parameters: {
    nativeComponent: 'badge',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Badge>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="badge" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
