// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { GridList } from '@tale-ui/react-native/grid-list';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { GridListAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['grid-list'];
const meta = {
  title: 'Components/Display/GridList',
  component: GridList,
  args: controls.args as Partial<React.ComponentProps<typeof GridList>>,
  argTypes: controls.argTypes as Meta<typeof GridList>['argTypes'],
  parameters: {
    nativeComponent: 'grid-list',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof GridList>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="grid-list" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
