// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { List } from '@tale-ui/react-native/list';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ListAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.list;
const meta = {
  title: 'Components/Display/List',
  component: List,
  args: controls.args as Partial<React.ComponentProps<typeof List>>,
  argTypes: controls.argTypes as Meta<typeof List>['argTypes'],
  parameters: {
    nativeComponent: 'list',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof List>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="list" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
