// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { ListBox } from '@tale-ui/react-native/list-box';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ListBoxAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['list-box'];
const meta = {
  title: 'Components/Display/ListBox',
  component: ListBox,
  args: controls.args as Partial<React.ComponentProps<typeof ListBox>>,
  argTypes: controls.argTypes as Meta<typeof ListBox>['argTypes'],
  parameters: {
    nativeComponent: 'list-box',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof ListBox>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="list-box" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
