// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { TagGroup } from '@tale-ui/react-native/tag-group';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { TagGroupAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['tag-group'];
const meta = {
  title: 'Components/Display/TagGroup',
  component: TagGroup,
  args: controls.args as Partial<React.ComponentProps<typeof TagGroup>>,
  argTypes: controls.argTypes as Meta<typeof TagGroup>['argTypes'],
  parameters: {
    nativeComponent: 'tag-group',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof TagGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="tag-group" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
