// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Banner } from '@tale-ui/react-native/banner';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { BannerAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.banner;
const meta = {
  title: 'Components/Feedback/Banner',
  component: Banner,
  args: controls.args as Partial<React.ComponentProps<typeof Banner>>,
  argTypes: controls.argTypes as Meta<typeof Banner>['argTypes'],
  parameters: {
    nativeComponent: 'banner',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Banner>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="banner" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
