// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { ProgressBar } from '@tale-ui/react-native/progress-bar';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ProgressBarAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['progress-bar'];
const meta = {
  title: 'Components/Feedback/ProgressBar',
  component: ProgressBar,
  args: controls.args as Partial<React.ComponentProps<typeof ProgressBar>>,
  argTypes: controls.argTypes as Meta<typeof ProgressBar>['argTypes'],
  parameters: {
    nativeComponent: 'progress-bar',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof ProgressBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="progress-bar" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
