// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Skeleton } from '@tale-ui/react-native/skeleton';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SkeletonAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.skeleton;
const meta = {
  title: 'Components/Feedback/Skeleton',
  component: Skeleton,
  args: controls.args as Partial<React.ComponentProps<typeof Skeleton>>,
  argTypes: controls.argTypes as Meta<typeof Skeleton>['argTypes'],
  parameters: {
    nativeComponent: 'skeleton',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Skeleton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="skeleton" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
