// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Spinner } from '@tale-ui/react-native/spinner';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { SpinnerAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.spinner;
const meta = {
  title: 'Components/Feedback/Spinner',
  component: Spinner,
  args: controls.args as Partial<React.ComponentProps<typeof Spinner>>,
  argTypes: controls.argTypes as Meta<typeof Spinner>['argTypes'],
  parameters: {
    nativeComponent: 'spinner',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Spinner>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="spinner" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
