// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Toast } from '@tale-ui/react-native/toast';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { ToastAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.toast;
const meta = {
  title: 'Components/Feedback/Toast',
  component: Toast,
  args: controls.args as Partial<React.ComponentProps<typeof Toast>>,
  argTypes: controls.argTypes as Meta<typeof Toast>['argTypes'],
  parameters: {
    nativeComponent: 'toast',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Toast>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="toast" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
