// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { resolveTheme } from '@tale-ui/foundations/theme';
import { harbourTheme } from '@tale-ui/foundations/theme-presets';

export type NativeStoryControlDefinition = Readonly<{
  args: Readonly<Record<string, unknown>>;
  argTypes: Readonly<Record<string, unknown>>;
  properties: readonly string[];
  actions: readonly string[];
}>;

const storybookTokens = resolveTheme(harbourTheme, 'light').tokens;

export const nativeStoryControls = {
  accordion: {
    args: {
      items: [
        {
          id: 'shipping',
          title: 'Shipping',
          content: 'Ships in 2–3 days.',
        },
        {
          id: 'returns',
          title: 'Returns',
          content: 'Returns accepted for 30 days.',
        },
      ],
      allowsMultipleExpanded: false,
      isDisabled: false,
    },
    argTypes: {
      items: {
        control: 'object',
        description: 'Accordion items. String content is adapted to native Text in the playground.',
      },
      allowsMultipleExpanded: {
        control: 'boolean',
        description: 'Allows more than one item to stay expanded.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables every accordion trigger.',
      },
    },
    properties: ['items', 'allowsMultipleExpanded', 'isDisabled'],
    actions: [],
  },
  'alert-dialog': {
    args: {
      isOpen: false,
      title: 'Delete draft',
      children: 'This action cannot be undone.',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the alert dialog is presented.',
      },
      title: {
        control: 'text',
        description: 'Accessible dialog heading.',
      },
      children: {
        control: 'text',
        description: 'Dialog body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'title', 'children'],
    actions: ['onOpenChange'],
  },
  badge: {
    args: {
      children: 'New',
      variant: 'neutral',
      size: 'md',
      type: 'pill',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Badge label.',
      },
      variant: {
        control: 'select',
        description: 'Badge colour treatment.',
        options: [
          'neutral',
          'brand',
          'error',
          'warning',
          'success',
          'red',
          'orange',
          'amber',
          'yellow',
          'lime',
          'green',
          'emerald',
          'teal',
          'cyan',
          'sky',
          'indigo',
          'violet',
          'purple',
          'fuchsia',
          'pink',
          'rose',
        ],
      },
      size: {
        control: 'select',
        description: 'Badge size.',
        options: ['sm', 'md', 'lg'],
      },
      type: {
        control: 'select',
        description: 'Badge shape treatment.',
        options: ['pill', 'rounded', 'modern'],
      },
    },
    properties: ['children', 'variant', 'size', 'type'],
    actions: [],
  },
  banner: {
    args: {
      title: 'Saved',
      children: 'Available offline.',
      variant: 'info',
      size: 'md',
    },
    argTypes: {
      title: {
        control: 'text',
        description: 'Banner heading.',
      },
      children: {
        control: 'text',
        description: 'Banner message.',
      },
      variant: {
        control: 'select',
        description: 'Semantic colour treatment.',
        options: ['info', 'success', 'warning', 'error'],
      },
      size: {
        control: 'select',
        description: 'Banner density.',
        options: ['sm', 'md'],
      },
    },
    properties: ['title', 'children', 'variant', 'size'],
    actions: [],
  },
  breadcrumbs: {
    args: {
      accessibilityLabel: 'Breadcrumbs',
      children: 'Home / Settings / Profile',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible navigation label.',
      },
      children: {
        control: 'text',
        description: 'Breadcrumb preview content.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  button: {
    args: {
      children: 'Continue',
      accessibilityLabel: 'Continue',
      isDisabled: false,
      isPending: false,
      variant: 'primary',
      size: 'md',
      showTextWhileLoading: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible button label.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Explicit accessible name.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      isPending: {
        control: 'boolean',
        description: 'Shows pending state and disables activation.',
      },
      variant: {
        control: 'select',
        description: 'Button visual treatment.',
        options: [
          'primary',
          'neutral',
          'ghost',
          'danger',
          'danger-neutral',
          'danger-ghost',
          'inverse',
        ],
      },
      size: {
        control: 'select',
        description: 'Button size.',
        options: ['sm', 'md', 'lg'],
      },
      showTextWhileLoading: {
        control: 'boolean',
        description: 'Keeps the label beside the pending spinner.',
      },
      onPress: {
        action: 'onPress',
        description: 'Reports button activation.',
        control: false,
      },
    },
    properties: [
      'children',
      'accessibilityLabel',
      'isDisabled',
      'isPending',
      'variant',
      'size',
      'showTextWhileLoading',
    ],
    actions: ['onPress'],
  },
  card: {
    args: {
      accessibilityLabel: 'Summary card',
      children: 'Card content',
      variant: 'outlined',
      padding: 'md',
      isSelected: false,
      isDisabled: false,
      isPending: false,
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible card label.',
      },
      children: {
        control: 'text',
        description: 'Card preview content.',
      },
      variant: {
        control: 'select',
        description: 'Card surface treatment.',
        options: ['outlined', 'elevated', 'filled'],
      },
      padding: {
        control: 'select',
        description: 'Card inner padding.',
        options: ['sm', 'md', 'lg'],
      },
      isSelected: {
        control: 'boolean',
        description: 'Applies the selected ring.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Applies disabled styling.',
      },
      isPending: {
        control: 'boolean',
        description: 'Applies pending styling.',
      },
      onPress: {
        action: 'onPress',
        description: 'Reports card activation.',
        control: false,
      },
    },
    properties: [
      'accessibilityLabel',
      'children',
      'variant',
      'padding',
      'isSelected',
      'isDisabled',
      'isPending',
    ],
    actions: ['onPress'],
  },
  'checkbox-field': {
    args: {
      children: 'Send updates',
      accessibilityLabel: 'Send updates',
      isSelected: false,
      isDisabled: false,
      size: 'md',
      isInvalid: false,
      isRequired: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Checkbox label.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Explicit accessible name.',
      },
      isSelected: {
        control: 'boolean',
        description: 'Controlled selected state.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables selection.',
      },
      size: {
        control: 'select',
        description: 'Checkbox indicator size.',
        options: ['sm', 'md'],
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      isRequired: {
        control: 'boolean',
        description: 'Marks the checkbox as required.',
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selection changes.',
        control: false,
      },
    },
    properties: [
      'children',
      'accessibilityLabel',
      'isSelected',
      'isDisabled',
      'size',
      'isInvalid',
      'isRequired',
    ],
    actions: ['onSelectionChange'],
  },
  'checkbox-group': {
    args: {
      accessibilityLabel: 'Notification choices',
      children: 'Email, Push, SMS',
      orientation: 'vertical',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible group label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated checkbox labels.',
      },
      orientation: {
        control: 'select',
        description: 'Choice layout direction.',
        options: ['vertical', 'horizontal'],
      },
    },
    properties: ['accessibilityLabel', 'children', 'orientation'],
    actions: [],
  },
  column: {
    args: {
      accessibilityLabel: 'Vertical stack',
      children: 'First, Second, Third',
      gap: 'm',
      align: 'stretch',
      justify: 'start',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible layout label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated child labels.',
      },
      gap: {
        control: 'select',
        description: 'Token gap between children.',
        options: ['4xs', '3xs', '2xs', 'xs', 's', 'm', 'l', 'xl', '2xl'],
      },
      align: {
        control: 'select',
        description: 'Cross-axis alignment.',
        options: ['start', 'center', 'end', 'stretch', 'baseline'],
      },
      justify: {
        control: 'select',
        description: 'Main-axis distribution.',
        options: ['start', 'center', 'end', 'between'],
      },
    },
    properties: ['accessibilityLabel', 'children', 'gap', 'align', 'justify'],
    actions: [],
  },
  dialog: {
    args: {
      isOpen: false,
      title: 'Account settings',
      children: 'Dialog content',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the dialog is presented.',
      },
      title: {
        control: 'text',
        description: 'Accessible dialog heading.',
      },
      children: {
        control: 'text',
        description: 'Dialog body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'title', 'children'],
    actions: ['onOpenChange'],
  },
  disclosure: {
    args: {
      title: 'More information',
      isExpanded: false,
      children: 'Additional native content.',
      isDisabled: false,
      align: 'start',
    },
    argTypes: {
      title: {
        control: 'text',
        description: 'Disclosure trigger label.',
      },
      isExpanded: {
        control: 'boolean',
        description: 'Controlled expanded state.',
      },
      children: {
        control: 'text',
        description: 'Disclosure panel content.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables the disclosure trigger.',
      },
      align: {
        control: 'select',
        description: 'Trigger alignment.',
        options: ['start', 'end'],
      },
      onExpandedChange: {
        action: 'onExpandedChange',
        description: 'Reports expansion changes.',
        control: false,
      },
    },
    properties: ['title', 'isExpanded', 'children', 'isDisabled', 'align'],
    actions: ['onExpandedChange'],
  },
  drawer: {
    args: {
      isOpen: false,
      label: 'Navigation drawer',
      children: 'Drawer content',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the drawer is presented.',
      },
      label: {
        control: 'text',
        description: 'Accessible drawer label.',
      },
      children: {
        control: 'text',
        description: 'Drawer body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'label', 'children'],
    actions: ['onOpenChange'],
  },
  field: {
    args: {
      label: 'Email',
      description: 'Used for account notifications.',
      errorMessage: '',
      isRequired: false,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Field label.',
      },
      description: {
        control: 'text',
        description: 'Supporting description.',
      },
      errorMessage: {
        control: 'text',
        description: 'Validation message; leave empty for a valid field.',
      },
      isRequired: {
        control: 'boolean',
        description: 'Marks the field as required.',
      },
    },
    properties: ['label', 'description', 'errorMessage', 'isRequired'],
    actions: [],
  },
  fieldset: {
    args: {
      legend: 'Contact preferences',
      disabled: false,
    },
    argTypes: {
      legend: {
        control: 'text',
        description: 'Accessible fieldset legend.',
      },
      disabled: {
        control: 'boolean',
        description: 'Applies disabled styling to the group.',
      },
    },
    properties: ['legend', 'disabled'],
    actions: [],
  },
  form: {
    args: {
      accessibilityLabel: 'Profile form',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible form label.',
      },
    },
    properties: ['accessibilityLabel'],
    actions: [],
  },
  'grid-list': {
    args: {
      label: 'Photo grid',
      children: 'One, Two, Three, Four',
      layout: 'list',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible grid label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated grid item labels.',
      },
      layout: {
        control: 'select',
        description: 'Native item layout.',
        options: ['list', 'grid'],
      },
    },
    properties: ['label', 'children', 'layout'],
    actions: [],
  },
  icon: {
    args: {
      label: 'Favourite',
      children: '★',
      size: 'md',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible label; empty makes it decorative.',
      },
      children: {
        control: 'text',
        description: 'Visible native glyph or icon content.',
      },
      size: {
        control: 'select',
        description: 'Icon wrapper size.',
        options: ['sm', 'md', 'lg', 'xl'],
      },
    },
    properties: ['label', 'children', 'size'],
    actions: [],
  },
  'icon-button': {
    args: {
      children: '+',
      accessibilityLabel: 'Add item',
      isDisabled: false,
      isPending: false,
      variant: 'ghost',
      size: 'md',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible icon glyph.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Required accessible name.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      isPending: {
        control: 'boolean',
        description: 'Shows pending state and disables activation.',
      },
      variant: {
        control: 'select',
        description: 'Button visual treatment.',
        options: ['primary', 'neutral', 'ghost', 'danger', 'inverse'],
      },
      size: {
        control: 'select',
        description: 'Icon button size.',
        options: ['sm', 'md', 'lg'],
      },
      onPress: {
        action: 'onPress',
        description: 'Reports button activation.',
        control: false,
      },
    },
    properties: ['children', 'accessibilityLabel', 'isDisabled', 'isPending', 'variant', 'size'],
    actions: ['onPress'],
  },
  input: {
    args: {
      accessibilityLabel: 'Email',
      placeholder: 'name@example.com',
      value: '',
      isDisabled: false,
      isInvalid: false,
      isReadOnly: false,
      size: 'md',
      secureTextEntry: false,
      keyboardType: 'default',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible input name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled input value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      isReadOnly: {
        control: 'boolean',
        description: 'Prevents editing without disabled opacity.',
      },
      size: {
        control: 'select',
        description: 'Field size.',
        options: ['sm', 'md', 'lg'],
      },
      secureTextEntry: {
        control: 'boolean',
        description: 'Masks entered text.',
      },
      keyboardType: {
        control: 'select',
        description: 'Native keyboard layout.',
        options: ['default', 'email-address', 'numeric', 'phone-pad'],
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports text changes.',
        control: false,
      },
    },
    properties: [
      'accessibilityLabel',
      'placeholder',
      'value',
      'isDisabled',
      'isInvalid',
      'isReadOnly',
      'size',
      'secureTextEntry',
      'keyboardType',
    ],
    actions: ['onChangeText'],
  },
  list: {
    args: {
      label: 'Messages',
      children: 'First message, Second message',
      variant: 'plain',
      density: 'default',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible list label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated item labels.',
      },
      variant: {
        control: 'select',
        description: 'List divider treatment.',
        options: ['plain', 'divided'],
      },
      density: {
        control: 'select',
        description: 'List item spacing.',
        options: ['compact', 'default', 'spacious'],
      },
    },
    properties: ['label', 'children', 'variant', 'density'],
    actions: [],
  },
  'list-box': {
    args: {
      label: 'Options',
      children: 'Selected option, Disabled option',
      frameless: false,
      layout: 'list',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible list-box label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated option labels.',
      },
      frameless: {
        control: 'boolean',
        description: 'Removes popup surface styling.',
      },
      layout: {
        control: 'select',
        description: 'List or grid layout.',
        options: ['list', 'grid'],
      },
    },
    properties: ['label', 'children', 'frameless', 'layout'],
    actions: [],
  },
  pagination: {
    args: {
      label: 'Pagination',
      page: 2,
      totalPages: 8,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible pagination label.',
      },
      page: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Current page.',
      },
      totalPages: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Total page count.',
      },
      onPageChange: {
        action: 'onPageChange',
        description: 'Reports requested page changes.',
        control: false,
      },
    },
    properties: ['label', 'page', 'totalPages'],
    actions: ['onPageChange'],
  },
  'progress-bar': {
    args: {
      label: 'Upload progress',
      value: 64,
      minValue: 0,
      maxValue: 100,
      labelPosition: 'top',
      isIndeterminate: false,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible progress label.',
      },
      value: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Current value.',
      },
      minValue: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Minimum value.',
      },
      maxValue: {
        control: {
          type: 'number',
          min: 1,
          max: 100,
          step: 1,
        },
        description: 'Maximum value.',
      },
      labelPosition: {
        control: 'select',
        description: 'Label and value position.',
        options: ['top', 'right', 'bottom', 'top-floating', 'bottom-floating'],
      },
      isIndeterminate: {
        control: 'boolean',
        description: 'Shows indeterminate progress.',
      },
    },
    properties: ['label', 'value', 'minValue', 'maxValue', 'labelPosition', 'isIndeterminate'],
    actions: [],
  },
  'radio-group': {
    args: {
      label: 'Delivery method',
      value: 'standard',
      items: [
        {
          value: 'standard',
          label: 'Standard',
        },
        {
          value: 'express',
          label: 'Express',
        },
      ],
      size: 'md',
      orientation: 'vertical',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible radio-group label.',
      },
      value: {
        control: 'select',
        description: 'Controlled selected value.',
        options: ['standard', 'express'],
      },
      items: {
        control: 'object',
        description: 'Radio choices.',
      },
      size: {
        control: 'select',
        description: 'Radio indicator size.',
        options: ['sm', 'md'],
      },
      orientation: {
        control: 'select',
        description: 'Choice layout direction.',
        options: ['vertical', 'horizontal'],
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports selected values.',
        control: false,
      },
    },
    properties: ['label', 'value', 'items', 'size', 'orientation'],
    actions: ['onValueChange'],
  },
  row: {
    args: {
      accessibilityLabel: 'Horizontal stack',
      children: 'First, Second, Third',
      gap: 'm',
      align: 'center',
      justify: 'start',
      wrap: false,
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible layout label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated child labels.',
      },
      gap: {
        control: 'select',
        description: 'Token gap between children.',
        options: ['4xs', '3xs', '2xs', 'xs', 's', 'm', 'l', 'xl', '2xl'],
      },
      align: {
        control: 'select',
        description: 'Cross-axis alignment.',
        options: ['start', 'center', 'end', 'stretch', 'baseline'],
      },
      justify: {
        control: 'select',
        description: 'Main-axis distribution.',
        options: ['start', 'center', 'end', 'between'],
      },
      wrap: {
        control: 'boolean',
        description: 'Allows children to wrap.',
      },
    },
    properties: ['accessibilityLabel', 'children', 'gap', 'align', 'justify', 'wrap'],
    actions: [],
  },
  'search-field': {
    args: {
      accessibilityLabel: 'Search',
      placeholder: 'Search components',
      value: '',
      isDisabled: false,
      isInvalid: false,
      variant: 'default',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible search name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled search value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      variant: {
        control: 'select',
        description: 'Search field visual treatment.',
        options: ['default', 'inline'],
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports query changes.',
        control: false,
      },
    },
    properties: [
      'accessibilityLabel',
      'placeholder',
      'value',
      'isDisabled',
      'isInvalid',
      'variant',
    ],
    actions: ['onChangeText'],
  },
  separator: {
    args: {
      accessibilityLabel: 'Section separator',
      orientation: 'horizontal',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Optional accessible description.',
      },
      orientation: {
        control: 'select',
        description: 'Separator orientation.',
        options: ['horizontal', 'vertical'],
      },
    },
    properties: ['accessibilityLabel', 'orientation'],
    actions: [],
  },
  skeleton: {
    args: {
      variant: 'text',
      animation: 'pulse',
    },
    argTypes: {
      variant: {
        control: 'select',
        description: 'Skeleton shape.',
        options: ['text', 'rectangular', 'circular'],
      },
      animation: {
        control: 'select',
        description: 'Skeleton animation treatment.',
        options: ['pulse', 'none'],
      },
    },
    properties: ['variant', 'animation'],
    actions: [],
  },
  slider: {
    args: {
      label: 'Volume',
      value: 40,
      minValue: 0,
      maxValue: 100,
      step: 5,
      isDisabled: false,
      orientation: 'horizontal',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible slider label.',
      },
      value: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Current value.',
      },
      minValue: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Minimum value.',
      },
      maxValue: {
        control: {
          type: 'number',
          min: 1,
          max: 100,
          step: 1,
        },
        description: 'Maximum value.',
      },
      step: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Accessibility action increment.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables adjustment.',
      },
      orientation: {
        control: 'select',
        description: 'Slider orientation.',
        options: ['horizontal', 'vertical'],
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports value changes.',
        control: false,
      },
    },
    properties: ['label', 'value', 'minValue', 'maxValue', 'step', 'isDisabled', 'orientation'],
    actions: ['onValueChange'],
  },
  spinner: {
    args: {
      animating: true,
      variant: 'circle',
      size: 'md',
      label: 'Loading',
      color: storybookTokens.color60,
    },
    argTypes: {
      animating: {
        control: 'boolean',
        description: 'Whether the spinner animates.',
      },
      variant: {
        control: 'select',
        description: 'Spinner animation style.',
        options: ['circle', 'line', 'dots'],
      },
      size: {
        control: 'select',
        description: 'Spinner size.',
        options: ['sm', 'md', 'lg'],
      },
      label: {
        control: 'text',
        description: 'Accessible loading label.',
      },
      color: {
        control: 'color',
        description: 'Spinner color.',
      },
    },
    properties: ['animating', 'variant', 'size', 'label', 'color'],
    actions: [],
  },
  'switch-field': {
    args: {
      label: 'Reduce notifications',
      value: false,
      disabled: false,
      isInvalid: false,
      isRequired: false,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Visible and accessible switch label.',
      },
      value: {
        control: 'boolean',
        description: 'Controlled switch state.',
      },
      disabled: {
        control: 'boolean',
        description: 'Disables interaction.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      isRequired: {
        control: 'boolean',
        description: 'Marks the switch as required.',
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports switch state changes.',
        control: false,
      },
    },
    properties: ['label', 'value', 'disabled', 'isInvalid', 'isRequired'],
    actions: ['onValueChange'],
  },
  tabs: {
    args: {
      selectedKey: 'one',
      items: [
        {
          id: 'one',
          label: 'Overview',
          content: 'Overview panel',
        },
        {
          id: 'two',
          label: 'Details',
          content: 'Details panel',
        },
      ],
      variant: 'underline',
      size: 'md',
      orientation: 'horizontal',
    },
    argTypes: {
      selectedKey: {
        control: 'select',
        description: 'Controlled selected tab.',
        options: ['one', 'two'],
      },
      items: {
        control: 'object',
        description: 'Tab labels and panel content.',
      },
      variant: {
        control: 'select',
        description: 'Tab visual treatment.',
        options: ['underline', 'pills', 'enclosed'],
      },
      size: {
        control: 'select',
        description: 'Tab size.',
        options: ['sm', 'md'],
      },
      orientation: {
        control: 'select',
        description: 'Tab orientation.',
        options: ['horizontal', 'vertical'],
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selected tab keys.',
        control: false,
      },
    },
    properties: ['selectedKey', 'items', 'variant', 'size', 'orientation'],
    actions: ['onSelectionChange'],
  },
  'tag-group': {
    args: {
      label: 'Topics',
      children: 'Design, Native, Accessibility',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible tag-group label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated tag labels.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  text: {
    args: {
      children: 'Text with dynamic type support',
      selectable: false,
      numberOfLines: 0,
      variant: 'text',
      size: 'm',
      color: 'default',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Displayed text.',
      },
      selectable: {
        control: 'boolean',
        description: 'Allows native text selection.',
      },
      numberOfLines: {
        control: {
          type: 'number',
          min: 0,
          max: 8,
          step: 1,
        },
        description: 'Maximum lines; zero means unlimited.',
      },
      variant: {
        control: 'select',
        description: 'Typography role.',
        options: ['display', 'heading', 'title', 'label', 'text', 'mono'],
      },
      size: {
        control: 'select',
        description: 'Typography size.',
        options: ['xs', 's', 'm', 'l'],
      },
      color: {
        control: 'select',
        description: 'Semantic text colour.',
        options: ['default', 'muted', 'accent'],
      },
    },
    properties: ['children', 'selectable', 'numberOfLines', 'variant', 'size', 'color'],
    actions: [],
  },
  'text-area': {
    args: {
      accessibilityLabel: 'Message',
      placeholder: 'Write a message',
      value: '',
      isDisabled: false,
      isInvalid: false,
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible text-area name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled text-area value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports text changes.',
        control: false,
      },
    },
    properties: ['accessibilityLabel', 'placeholder', 'value', 'isDisabled', 'isInvalid'],
    actions: ['onChangeText'],
  },
  toast: {
    args: {
      label: 'Saved notification',
      children: 'Changes saved.',
      variant: 'neutral',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible notification label.',
      },
      children: {
        control: 'text',
        description: 'Notification message.',
      },
      variant: {
        control: 'select',
        description: 'Notification accent.',
        options: ['neutral', 'success', 'warning', 'danger'],
      },
    },
    properties: ['label', 'children', 'variant'],
    actions: [],
  },
  'toggle-button': {
    args: {
      children: 'Bold',
      isSelected: false,
      isDisabled: false,
      size: 'md',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible toggle label.',
      },
      isSelected: {
        control: 'boolean',
        description: 'Controlled selected state.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      size: {
        control: 'select',
        description: 'Toggle button size.',
        options: ['sm', 'md', 'lg'],
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selection changes.',
        control: false,
      },
    },
    properties: ['children', 'isSelected', 'isDisabled', 'size'],
    actions: ['onSelectionChange'],
  },
  'toggle-group': {
    args: {
      children: 'Bold, Italic, Underline',
      accessibilityLabel: 'Text formatting',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Comma-separated toggle labels.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible group label.',
      },
    },
    properties: ['children', 'accessibilityLabel'],
    actions: [],
  },
  toolbar: {
    args: {
      accessibilityLabel: 'Editing toolbar',
      children: 'Undo, Redo',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible toolbar label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated toolbar action labels.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
} as const satisfies Record<string, NativeStoryControlDefinition>;
