// Generated by tools/generate-react-native-stories.mjs. Do not edit.

export type NativeStoryControlDefinition = Readonly<{
  args: Readonly<Record<string, unknown>>;
  argTypes: Readonly<Record<string, unknown>>;
  properties: readonly string[];
  actions: readonly string[];
}>;

export const nativeStoryControls = {
  accordion: {
    args: {
      items: [
        {
          id: 'shipping',
          title: 'Shipping',
          content: 'Ships in 2–3 days.',
        },
        {
          id: 'returns',
          title: 'Returns',
          content: 'Returns accepted for 30 days.',
        },
      ],
    },
    argTypes: {
      items: {
        control: 'object',
        description: 'Accordion items. String content is adapted to native Text in the playground.',
      },
    },
    properties: ['items'],
    actions: [],
  },
  'alert-dialog': {
    args: {
      isOpen: false,
      title: 'Delete draft',
      children: 'This action cannot be undone.',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the alert dialog is presented.',
      },
      title: {
        control: 'text',
        description: 'Accessible dialog heading.',
      },
      children: {
        control: 'text',
        description: 'Dialog body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'title', 'children'],
    actions: ['onOpenChange'],
  },
  badge: {
    args: {
      children: 'New',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Badge label.',
      },
    },
    properties: ['children'],
    actions: [],
  },
  banner: {
    args: {
      title: 'Saved',
      children: 'Available offline.',
    },
    argTypes: {
      title: {
        control: 'text',
        description: 'Banner heading.',
      },
      children: {
        control: 'text',
        description: 'Banner message.',
      },
    },
    properties: ['title', 'children'],
    actions: [],
  },
  breadcrumbs: {
    args: {
      accessibilityLabel: 'Breadcrumbs',
      children: 'Home / Settings / Profile',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible navigation label.',
      },
      children: {
        control: 'text',
        description: 'Breadcrumb preview content.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  button: {
    args: {
      children: 'Continue',
      accessibilityLabel: 'Continue',
      isDisabled: false,
      isPending: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible button label.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Explicit accessible name.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      isPending: {
        control: 'boolean',
        description: 'Shows pending state and disables activation.',
      },
      onPress: {
        action: 'onPress',
        description: 'Reports button activation.',
        control: false,
      },
    },
    properties: ['children', 'accessibilityLabel', 'isDisabled', 'isPending'],
    actions: ['onPress'],
  },
  card: {
    args: {
      accessibilityLabel: 'Summary card',
      children: 'Card content',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible card label.',
      },
      children: {
        control: 'text',
        description: 'Card preview content.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  'checkbox-field': {
    args: {
      children: 'Send updates',
      accessibilityLabel: 'Send updates',
      isSelected: false,
      isDisabled: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Checkbox label.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Explicit accessible name.',
      },
      isSelected: {
        control: 'boolean',
        description: 'Controlled selected state.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables selection.',
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selection changes.',
        control: false,
      },
    },
    properties: ['children', 'accessibilityLabel', 'isSelected', 'isDisabled'],
    actions: ['onSelectionChange'],
  },
  'checkbox-group': {
    args: {
      accessibilityLabel: 'Notification choices',
      children: 'Email, Push, SMS',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible group label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated checkbox labels.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  column: {
    args: {
      accessibilityLabel: 'Vertical stack',
      children: 'First, Second, Third',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible layout label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated child labels.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  dialog: {
    args: {
      isOpen: false,
      title: 'Account settings',
      children: 'Dialog content',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the dialog is presented.',
      },
      title: {
        control: 'text',
        description: 'Accessible dialog heading.',
      },
      children: {
        control: 'text',
        description: 'Dialog body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'title', 'children'],
    actions: ['onOpenChange'],
  },
  disclosure: {
    args: {
      title: 'More information',
      isExpanded: false,
      children: 'Additional native content.',
    },
    argTypes: {
      title: {
        control: 'text',
        description: 'Disclosure trigger label.',
      },
      isExpanded: {
        control: 'boolean',
        description: 'Controlled expanded state.',
      },
      children: {
        control: 'text',
        description: 'Disclosure panel content.',
      },
      onExpandedChange: {
        action: 'onExpandedChange',
        description: 'Reports expansion changes.',
        control: false,
      },
    },
    properties: ['title', 'isExpanded', 'children'],
    actions: ['onExpandedChange'],
  },
  drawer: {
    args: {
      isOpen: false,
      label: 'Navigation drawer',
      children: 'Drawer content',
    },
    argTypes: {
      isOpen: {
        control: 'boolean',
        description: 'Whether the drawer is presented.',
      },
      label: {
        control: 'text',
        description: 'Accessible drawer label.',
      },
      children: {
        control: 'text',
        description: 'Drawer body copy.',
      },
      onOpenChange: {
        action: 'onOpenChange',
        description: 'Reports open and close requests.',
        control: false,
      },
    },
    properties: ['isOpen', 'label', 'children'],
    actions: ['onOpenChange'],
  },
  field: {
    args: {
      label: 'Email',
      description: 'Used for account notifications.',
      errorMessage: '',
      isRequired: false,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Field label.',
      },
      description: {
        control: 'text',
        description: 'Supporting description.',
      },
      errorMessage: {
        control: 'text',
        description: 'Validation message; leave empty for a valid field.',
      },
      isRequired: {
        control: 'boolean',
        description: 'Marks the field as required.',
      },
    },
    properties: ['label', 'description', 'errorMessage', 'isRequired'],
    actions: [],
  },
  fieldset: {
    args: {
      legend: 'Contact preferences',
    },
    argTypes: {
      legend: {
        control: 'text',
        description: 'Accessible fieldset legend.',
      },
    },
    properties: ['legend'],
    actions: [],
  },
  form: {
    args: {
      accessibilityLabel: 'Profile form',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible form label.',
      },
    },
    properties: ['accessibilityLabel'],
    actions: [],
  },
  'grid-list': {
    args: {
      label: 'Photo grid',
      children: 'One, Two, Three, Four',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible grid label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated grid item labels.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  icon: {
    args: {
      label: 'Favourite',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible label; empty makes it decorative.',
      },
    },
    properties: ['label'],
    actions: [],
  },
  'icon-button': {
    args: {
      children: '+',
      accessibilityLabel: 'Add item',
      isDisabled: false,
      isPending: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible icon glyph.',
      },
      accessibilityLabel: {
        control: 'text',
        description: 'Required accessible name.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      isPending: {
        control: 'boolean',
        description: 'Shows pending state and disables activation.',
      },
      onPress: {
        action: 'onPress',
        description: 'Reports button activation.',
        control: false,
      },
    },
    properties: ['children', 'accessibilityLabel', 'isDisabled', 'isPending'],
    actions: ['onPress'],
  },
  input: {
    args: {
      accessibilityLabel: 'Email',
      placeholder: 'name@example.com',
      value: '',
      isDisabled: false,
      isInvalid: false,
      secureTextEntry: false,
      keyboardType: 'default',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible input name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled input value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      secureTextEntry: {
        control: 'boolean',
        description: 'Masks entered text.',
      },
      keyboardType: {
        control: 'select',
        description: 'Native keyboard layout.',
        options: ['default', 'email-address', 'numeric', 'phone-pad'],
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports text changes.',
        control: false,
      },
    },
    properties: [
      'accessibilityLabel',
      'placeholder',
      'value',
      'isDisabled',
      'isInvalid',
      'secureTextEntry',
      'keyboardType',
    ],
    actions: ['onChangeText'],
  },
  list: {
    args: {
      label: 'Messages',
      children: 'First message, Second message',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible list label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated item labels.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  'list-box': {
    args: {
      label: 'Options',
      children: 'Selected option, Disabled option',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible list-box label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated option labels.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  pagination: {
    args: {
      page: 2,
      totalPages: 8,
    },
    argTypes: {
      page: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Current page.',
      },
      totalPages: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Total page count.',
      },
      onPageChange: {
        action: 'onPageChange',
        description: 'Reports requested page changes.',
        control: false,
      },
    },
    properties: ['page', 'totalPages'],
    actions: ['onPageChange'],
  },
  'progress-bar': {
    args: {
      label: 'Upload progress',
      value: 64,
      minValue: 0,
      maxValue: 100,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible progress label.',
      },
      value: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Current value.',
      },
      minValue: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Minimum value.',
      },
      maxValue: {
        control: {
          type: 'number',
          min: 1,
          max: 100,
          step: 1,
        },
        description: 'Maximum value.',
      },
    },
    properties: ['label', 'value', 'minValue', 'maxValue'],
    actions: [],
  },
  'radio-field': {
    args: {
      label: 'Delivery method',
      value: 'standard',
      items: [
        {
          value: 'standard',
          label: 'Standard',
        },
        {
          value: 'express',
          label: 'Express',
        },
      ],
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible radio-field label.',
      },
      value: {
        control: 'select',
        description: 'Controlled selected value.',
        options: ['standard', 'express'],
      },
      items: {
        control: 'object',
        description: 'Radio choices.',
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports selected values.',
        control: false,
      },
    },
    properties: ['label', 'value', 'items'],
    actions: ['onValueChange'],
  },
  'radio-group': {
    args: {
      label: 'Delivery method',
      value: 'standard',
      items: [
        {
          value: 'standard',
          label: 'Standard',
        },
        {
          value: 'express',
          label: 'Express',
        },
      ],
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible radio-group label.',
      },
      value: {
        control: 'select',
        description: 'Controlled selected value.',
        options: ['standard', 'express'],
      },
      items: {
        control: 'object',
        description: 'Radio choices.',
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports selected values.',
        control: false,
      },
    },
    properties: ['label', 'value', 'items'],
    actions: ['onValueChange'],
  },
  row: {
    args: {
      accessibilityLabel: 'Horizontal stack',
      children: 'First, Second, Third',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible layout label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated child labels.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
  'search-field': {
    args: {
      accessibilityLabel: 'Search',
      placeholder: 'Search components',
      value: '',
      isDisabled: false,
      isInvalid: false,
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible search name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled search value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports query changes.',
        control: false,
      },
    },
    properties: ['accessibilityLabel', 'placeholder', 'value', 'isDisabled', 'isInvalid'],
    actions: ['onChangeText'],
  },
  separator: {
    args: {
      accessibilityLabel: 'Section separator',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Optional accessible description.',
      },
    },
    properties: ['accessibilityLabel'],
    actions: [],
  },
  slider: {
    args: {
      label: 'Volume',
      value: 40,
      minValue: 0,
      maxValue: 100,
      step: 5,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible slider label.',
      },
      value: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Current value.',
      },
      minValue: {
        control: {
          type: 'number',
          min: 0,
          max: 100,
          step: 1,
        },
        description: 'Minimum value.',
      },
      maxValue: {
        control: {
          type: 'number',
          min: 1,
          max: 100,
          step: 1,
        },
        description: 'Maximum value.',
      },
      step: {
        control: {
          type: 'number',
          min: 1,
          max: 20,
          step: 1,
        },
        description: 'Accessibility action increment.',
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports value changes.',
        control: false,
      },
    },
    properties: ['label', 'value', 'minValue', 'maxValue', 'step'],
    actions: ['onValueChange'],
  },
  spinner: {
    args: {
      animating: true,
      size: 'small',
      color: '#025768',
    },
    argTypes: {
      animating: {
        control: 'boolean',
        description: 'Whether the spinner animates.',
      },
      size: {
        control: 'select',
        description: 'Native spinner size.',
        options: ['small', 'large'],
      },
      color: {
        control: 'color',
        description: 'Spinner color.',
      },
    },
    properties: ['animating', 'size', 'color'],
    actions: [],
  },
  'switch-field': {
    args: {
      label: 'Reduce notifications',
      value: false,
      disabled: false,
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Visible and accessible switch label.',
      },
      value: {
        control: 'boolean',
        description: 'Controlled switch state.',
      },
      disabled: {
        control: 'boolean',
        description: 'Disables interaction.',
      },
      onValueChange: {
        action: 'onValueChange',
        description: 'Reports switch state changes.',
        control: false,
      },
    },
    properties: ['label', 'value', 'disabled'],
    actions: ['onValueChange'],
  },
  tabs: {
    args: {
      selectedKey: 'one',
      items: [
        {
          id: 'one',
          label: 'Overview',
          content: 'Overview panel',
        },
        {
          id: 'two',
          label: 'Details',
          content: 'Details panel',
        },
      ],
    },
    argTypes: {
      selectedKey: {
        control: 'select',
        description: 'Controlled selected tab.',
        options: ['one', 'two'],
      },
      items: {
        control: 'object',
        description: 'Tab labels and panel content.',
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selected tab keys.',
        control: false,
      },
    },
    properties: ['selectedKey', 'items'],
    actions: ['onSelectionChange'],
  },
  'tag-group': {
    args: {
      label: 'Topics',
      children: 'Design, Native, Accessibility',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible tag-group label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated tag labels.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  text: {
    args: {
      children: 'Text with dynamic type support',
      selectable: false,
      numberOfLines: 0,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Displayed text.',
      },
      selectable: {
        control: 'boolean',
        description: 'Allows native text selection.',
      },
      numberOfLines: {
        control: {
          type: 'number',
          min: 0,
          max: 8,
          step: 1,
        },
        description: 'Maximum lines; zero means unlimited.',
      },
    },
    properties: ['children', 'selectable', 'numberOfLines'],
    actions: [],
  },
  'text-area': {
    args: {
      accessibilityLabel: 'Message',
      placeholder: 'Write a message',
      value: '',
      isDisabled: false,
      isInvalid: false,
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible text-area name.',
      },
      placeholder: {
        control: 'text',
        description: 'Placeholder text.',
      },
      value: {
        control: 'text',
        description: 'Controlled text-area value.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables editing.',
      },
      isInvalid: {
        control: 'boolean',
        description: 'Applies invalid styling.',
      },
      onChangeText: {
        action: 'onChangeText',
        description: 'Reports text changes.',
        control: false,
      },
    },
    properties: ['accessibilityLabel', 'placeholder', 'value', 'isDisabled', 'isInvalid'],
    actions: ['onChangeText'],
  },
  toast: {
    args: {
      label: 'Saved notification',
      children: 'Changes saved.',
    },
    argTypes: {
      label: {
        control: 'text',
        description: 'Accessible notification label.',
      },
      children: {
        control: 'text',
        description: 'Notification message.',
      },
    },
    properties: ['label', 'children'],
    actions: [],
  },
  'toggle-button': {
    args: {
      children: 'Bold',
      isSelected: false,
      isDisabled: false,
      isPending: false,
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Visible toggle label.',
      },
      isSelected: {
        control: 'boolean',
        description: 'Controlled selected state.',
      },
      isDisabled: {
        control: 'boolean',
        description: 'Disables activation.',
      },
      isPending: {
        control: 'boolean',
        description: 'Shows pending state and disables activation.',
      },
      onSelectionChange: {
        action: 'onSelectionChange',
        description: 'Reports selection changes.',
        control: false,
      },
    },
    properties: ['children', 'isSelected', 'isDisabled', 'isPending'],
    actions: ['onSelectionChange'],
  },
  'toggle-group': {
    args: {
      children: 'Bold, Italic, Underline',
    },
    argTypes: {
      children: {
        control: 'text',
        description: 'Comma-separated toggle labels.',
      },
    },
    properties: ['children'],
    actions: [],
  },
  toolbar: {
    args: {
      accessibilityLabel: 'Editing toolbar',
      children: 'Undo, Redo',
    },
    argTypes: {
      accessibilityLabel: {
        control: 'text',
        description: 'Accessible toolbar label.',
      },
      children: {
        control: 'text',
        description: 'Comma-separated toolbar action labels.',
      },
    },
    properties: ['accessibilityLabel', 'children'],
    actions: [],
  },
} as const satisfies Record<string, NativeStoryControlDefinition>;
