// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Field } from '@tale-ui/react-native/field';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { FieldAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.field;
const meta = {
  title: 'Components/Form Structure/Field',
  component: Field,
  args: controls.args as Partial<React.ComponentProps<typeof Field>>,
  argTypes: controls.argTypes as Meta<typeof Field>['argTypes'],
  parameters: {
    nativeComponent: 'field',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Field>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="field" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
