// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Fieldset } from '@tale-ui/react-native/fieldset';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { FieldsetAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.fieldset;
const meta = {
  title: 'Components/Form Structure/Fieldset',
  component: Fieldset,
  args: controls.args as Partial<React.ComponentProps<typeof Fieldset>>,
  argTypes: controls.argTypes as Meta<typeof Fieldset>['argTypes'],
  parameters: {
    nativeComponent: 'fieldset',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Fieldset>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="fieldset" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
