// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Form } from '@tale-ui/react-native/form';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { FormAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.form;
const meta = {
  title: 'Components/Form Structure/Form',
  component: Form,
  args: controls.args as Partial<React.ComponentProps<typeof Form>>,
  argTypes: controls.argTypes as Meta<typeof Form>['argTypes'],
  parameters: {
    nativeComponent: 'form',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Form>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="form" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
