// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Icon } from '@tale-ui/react-native/icon';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { IconAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.icon;
const meta = {
  title: 'Components/Utility/Icon',
  component: Icon,
  args: controls.args as Partial<React.ComponentProps<typeof Icon>>,
  argTypes: controls.argTypes as Meta<typeof Icon>['argTypes'],
  parameters: {
    nativeComponent: 'icon',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Icon>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="icon" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
