// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { IconButton } from '@tale-ui/react-native/icon-button';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { IconButtonAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['icon-button'];
const meta = {
  title: 'Components/Utility/IconButton',
  component: IconButton,
  args: controls.args as Partial<React.ComponentProps<typeof IconButton>>,
  argTypes: controls.argTypes as Meta<typeof IconButton>['argTypes'],
  parameters: {
    nativeComponent: 'icon-button',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof IconButton>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="icon-button" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
