// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { AlertDialog } from '@tale-ui/react-native/alert-dialog';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { AlertDialogAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls['alert-dialog'];
const meta = {
  title: 'Components/Overlay/AlertDialog',
  component: AlertDialog,
  args: controls.args as Partial<React.ComponentProps<typeof AlertDialog>>,
  argTypes: controls.argTypes as Meta<typeof AlertDialog>['argTypes'],
  parameters: {
    nativeComponent: 'alert-dialog',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof AlertDialog>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="alert-dialog" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
