// Generated by tools/generate-react-native-stories.mjs. Do not edit.

import { Drawer } from '@tale-ui/react-native/drawer';
import type { Meta, StoryObj } from '@storybook/react-native';
import type * as React from 'react';
import { NativePlayground } from '../../NativePlayground';
import { nativeStoryControls } from '../../NativeStoryControls';
import { DrawerAllVariations as allVariationsFixture } from '../../Registry.fixtures';

const controls = nativeStoryControls.drawer;
const meta = {
  title: 'Components/Overlay/Drawer',
  component: Drawer,
  args: controls.args as Partial<React.ComponentProps<typeof Drawer>>,
  argTypes: controls.argTypes as Meta<typeof Drawer>['argTypes'],
  parameters: {
    nativeComponent: 'drawer',
    nativeControls: controls.properties,
    nativeActions: controls.actions,
  },
} satisfies Meta<typeof Drawer>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Playground: Story = {
  render: (args) => <NativePlayground args={args} component="drawer" />,
};

export const AllVariations: Story = {
  name: 'All Variations',
  render: allVariationsFixture.render as Story['render'],
};
